### ISSUE TITLE
Rendering not working

### ISSUE THREAD

**Issue by gregbritten** [abezukor/EquationEditorPP#3] opened 2021-03-21 15:24 UTC
The Latex box is not rendering. The dpi options are also not longer visible. 
It may be related to the CodeCogs service as I notice this on their forum this morning:

![image](https://user-images.githubusercontent.com/19557522/111910473-e2552f80-8a37-11eb-9aa2-738322af17ff.png)

**Comment by abezukor** [comment] 2023-07-08 18:07
The entire rendering pipeline was re-done in an update last month, so I am closing this issue. Feel free to leave another comment if it pops back up. I have moved away from codecogs rendering as I believe it was the cause of #2.

**Closed as completed by abezukor** 2023-07-08 18:07 UTC
